# Generated by Django 4.1 on 2022-08-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse_mail', models.EmailField(max_length=500)),
                ('region', models.CharField(choices=[('Ariana', 'Ariana'), ('Tunis', 'Tunis'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Beja', 'Beja'), ('Bizerte', 'Bizerte'), ('Gabes', 'Gabes'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kebili', 'Kebili'), ('Kef', 'Kef'), ('Mahdia', 'Mahdia'), ('Medenine', 'Medenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Zaghouan', 'Zaghouan')], default='Tunis', max_length=20)),
                ('photo', models.ImageField(upload_to='cars/fichierExpert/photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='adresse_mail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsTestApp.client'),
        ),
    ]
