# Generated by Django 4.1 on 2022-08-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0002_client_expert_remove_user_adresse_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
    ]
