# Generated by Django 4.1 on 2022-08-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0003_remove_expert_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='vendeur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carsTestApp.client'),
        ),
    ]
