# Generated by Django 4.1 on 2022-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0004_alter_offre_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
