# Generated by Django 4.1 on 2022-08-20 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0007_alter_offre_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan_expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('batterie_cmd_electronique', models.CharField(max_length=200)),
                ('tableau_de_bord_alertes_temoins_allumes', models.CharField(max_length=200)),
                ('moteur_niveaux', models.CharField(max_length=200)),
                ('fixation', models.CharField(max_length=200)),
                ('courroies_accessoires', models.CharField(max_length=200)),
                ('boite_vitesse_embrayage', models.CharField(max_length=200)),
                ('echappement_pollution', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=200)),
                ('vision_eclairage_avertisseur_sonore', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('train', models.CharField(max_length=200)),
                ('transmission_roulement', models.CharField(max_length=200)),
                ('jantes_pneus', models.CharField(max_length=200)),
                ('freinage', models.CharField(max_length=200)),
                ('suspension', models.CharField(max_length=200)),
                ('infrastructure', models.CharField(max_length=200)),
                ('aspect_carrosserie', models.CharField(max_length=200)),
                ('interieur', models.CharField(max_length=200)),
                ('clim_chauffage', models.CharField(max_length=200)),
                ('essai_routier', models.CharField(max_length=200)),
                ('commentaire', models.TextField()),
                ('expert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
