# Generated by Django 4.1 on 2022-08-21 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0008_bilan_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_expert',
            name='expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to=settings.AUTH_USER_MODEL),
        ),
    ]
