# Generated by Django 4.1 on 2022-08-21 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0009_alter_bilan_expert_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expert_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
