# Generated by Django 4.1 on 2022-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0010_alter_expert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='annee',
            field=models.IntegerField(default=2000, verbose_name='année'),
        ),
    ]
