# Generated by Django 4.1 on 2022-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0014_alter_offre_prix_enchere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_expert',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
