# Generated by Django 4.1 on 2022-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0015_alter_bilan_expert_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
    ]
