# Generated by Django 4.1 on 2022-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0016_expert_notifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='nbre_notification',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
