# Generated by Django 4.1 on 2022-08-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0020_expert_nbre_notification_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='nbre_notification',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre', models.IntegerField(blank=True, default=0, null=True)),
                ('client_not', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_notification', to='carsTestApp.expert')),
                ('exp_not', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exp_notification', to='carsTestApp.expert')),
            ],
        ),
    ]
