# Generated by Django 4.1 on 2022-08-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0022_remove_notification_nbre_notification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
