# Generated by Django 4.1 on 2022-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0023_alter_notification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ident',
            field=models.IntegerField(default=100),
        ),
    ]
