# Generated by Django 4.1 on 2022-08-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0024_notification_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='client_not',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_notification', to='carsTestApp.client'),
        ),
    ]
