# Generated by Django 4.1 on 2022-08-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0025_alter_notification_client_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='client_not',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
