# Generated by Django 4.1 on 2022-08-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0028_alter_offre_expert_alter_offre_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='bilan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilan_offre', to='carsTestApp.bilan_expert'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_offre', to='carsTestApp.expert'),
        ),
    ]
