# Generated by Django 4.1 on 2022-08-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0029_alter_offre_bilan_alter_offre_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='vendeur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_offre', to=settings.AUTH_USER_MODEL),
        ),
    ]
