# Generated by Django 4.1 on 2022-08-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0030_alter_offre_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='bilan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricule', to='carsTestApp.bilan_expert'),
        ),
    ]
