# Generated by Django 4.1 on 2022-08-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0033_expert_numero_de_téléphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_expert',
            name='expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='carsTestApp.expert'),
        ),
    ]
