# Generated by Django 4.1 on 2022-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0034_alter_bilan_expert_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='matricule',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
