# Generated by Django 4.1 on 2022-08-28 19:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsTestApp', '0037_alter_offre_bilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan_expert',
            name='note',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='bilan_expert',
            name='prix_suggéré',
            field=models.FloatField(default=0),
        ),
    ]
